# Generated by Django 3.0.4 on 2020-03-14 04:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20200314_0331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doc', models.CharField(max_length=255)),
                ('sig_sender', models.CharField(max_length=100)),
                ('sig_receiver', models.CharField(max_length=100, null=True)),
                ('session_id', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('notified', 'Notified'), ('sending', 'Sending'), ('completed', 'Completed')], default='requested', max_length=100)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='user.User', to_field='user_id')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='user.User', to_field='user_id')),
            ],
            options={
                'db_table': 'ttp_document',
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['session_id'], name='ttp_documen_session_27171c_idx'),
        ),
    ]
