# Generated by Django 3.0.4 on 2020-03-14 02:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('public_key', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ttp_users',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_id'], name='ttp_users_user_id_3e8224_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['name'], name='ttp_users_name_92fae7_idx'),
        ),
    ]
